### ISSUE TITLE
Question on contribution

### ISSUE THREAD

**Issue by jesseokeya** [ok3dotdev/Expensify#1]
Is this a `mint.com` alternative. If so can I contribute to this?

**Comment by ok3dotdev** [comment]
Yes, you can contribute to the project. 
Any features you have In mind?

**Comment by jesseokeya** [comment]
Nice. No feature in particular was just about building a mint.com alternative for personal use but good thing I stumbled on this. I assume that eventually there will be a mobile app as well ?. Will clone this and try getting it running

**Comment by ok3dotdev** [comment]
sounds good. You can fork/clone the multiple-banks-branch it's the most up-to-date version. and has some instructions on env and how to run the app in the README. 

I'm a bit occupied today but I will add more docs if you have trouble getting it to run.

**Comment by jesseokeya** [comment]
Thanks. I got it running but have occasional errors with plaid and lemon squeezy. Created a test neon serverless db and clerk account to get the API key.

small [PR](https://github.com/ok3dotdev/Expensify/pull/2) with minor changes made. Do you have a `slack` channel for this project?

**Comment by ok3dotdev** [comment]
sent a slack invite
